name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the feature
      placeholder: What do you want to add or improve?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: Explain the use case and benefits
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: List any alternatives and why they were not chosen
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area does this feature affect?
      options:
        - Documentation
        - Core Specification
        - Runtime / Prompts
        - Benchmark
        - Tooling
        - CI/CD
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
